from dataclasses import dataclass

__all__ = ['AgentBudget', 'UnlimitedBudget']

@dataclass(frozen=True)
class AgentBudget:
    max_seconds: float | None = ...
    max_tool_calls: int | None = ...
    failure_budget: int | None = ...
    max_input_tokens: int | None = ...
    max_output_tokens: int | None = ...
    max_total_cost_micros_usd: int | None = ...

def UnlimitedBudget() -> AgentBudget: ...
