from _typeshed import Incomplete
from agentic_exception_sdk.budget.watchdog import BudgetWatchdog
from collections.abc import AsyncGenerator, AsyncIterable, Callable, Generator, Iterable
from typing import Literal, TypeVar

__all__ = ['StreamingBudgetGuard']

T = TypeVar('T')

class StreamingBudgetGuard:
    watchdog: Incomplete
    tool_name: Incomplete
    agent_id: Incomplete
    correlation_id: Incomplete
    total_tokens_streamed: int
    total_cost_streamed: float
    def __init__(self, watchdog: BudgetWatchdog, *, tool_name: str, agent_id: str, correlation_id: str | None = None) -> None: ...
    def __enter__(self) -> StreamingBudgetGuard: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, traceback: object | None) -> Literal[False]: ...
    async def __aenter__(self) -> StreamingBudgetGuard: ...
    async def __aexit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, traceback: object | None) -> Literal[False]: ...
    def record_chunk(self, token_delta: int = 1, cost_delta: float = 0.0) -> None: ...
    async def arecord_chunk(self, token_delta: int = 1, cost_delta: float = 0.0) -> None: ...
    @classmethod
    def wrap_sync_stream(cls, stream: Iterable[T], watchdog: BudgetWatchdog, *, tool_name: str, agent_id: str, token_extractor: Callable[[T], int] = ..., cost_extractor: Callable[[T], float] = ...) -> Generator[T, None, None]: ...
    @classmethod
    async def awrap_async_stream(cls, stream: AsyncIterable[T], watchdog: BudgetWatchdog, *, tool_name: str, agent_id: str, token_extractor: Callable[[T], int] = ..., cost_extractor: Callable[[T], float] = ...) -> AsyncGenerator[T, None]: ...
