from agentic_exception_sdk.budget.models import AgentBudget

__all__ = ['BudgetWatchdog']

class BudgetWatchdog:
    def __init__(self, budget: AgentBudget) -> None: ...
    def consume_call(self) -> None: ...
    def record_failure(self) -> None: ...
    def check_time(self) -> None: ...
    def check_before_sleep(self, sleep_seconds: float) -> None: ...
    def reserve_tokens(self, *, input_tokens: int = 0, output_tokens: int = 0, cost_micros_usd: int = 0) -> None: ...
    async def async_reserve_tokens(self, *, input_tokens: int = 0, output_tokens: int = 0, cost_micros_usd: int = 0) -> None: ...
    def account_stream_delta(self, *, input_tokens: int = 0, output_tokens: int = 0, cost_micros_usd: int = 0) -> None: ...
    def snapshot(self) -> dict[str, int | float | None]: ...
    @property
    def call_count(self) -> int: ...
    @property
    def failure_count(self) -> int: ...
    @property
    def input_tokens_used(self) -> int: ...
    @property
    def output_tokens_used(self) -> int: ...
    @property
    def cost_micros_used(self) -> int: ...
