from _typeshed import Incomplete
from agentic_exception_sdk.taxonomy.envelope import AgentExceptionEnvelope
from dataclasses import dataclass, field
from typing import Any, Protocol

__all__ = ['InMemoryMetricsCollector', 'MetricsCollector', 'NoOpMetricsCollector', 'PrometheusMetricsCollector']

class MetricsCollector(Protocol):
    def record_exception(self, envelope: AgentExceptionEnvelope) -> None: ...
    def record_hard_kill(self, agent_id: str | None = None) -> None: ...
    def record_retry(self, agent_id: str | None = None) -> None: ...
    def record_budget_exhausted(self) -> None: ...

class NoOpMetricsCollector:
    def record_exception(self, envelope: AgentExceptionEnvelope) -> None: ...
    def record_hard_kill(self, agent_id: str | None = None) -> None: ...
    def record_retry(self, agent_id: str | None = None) -> None: ...
    def record_budget_exhausted(self) -> None: ...

@dataclass
class InMemoryMetricsCollector:
    exception_counts: dict[str, int] = field(default_factory=Incomplete)
    hard_kill_total: int = ...
    retry_total: int = ...
    budget_exhausted_total: int = ...
    def record_exception(self, envelope: AgentExceptionEnvelope) -> None: ...
    def record_hard_kill(self, agent_id: str | None = None) -> None: ...
    def record_retry(self, agent_id: str | None = None) -> None: ...
    def record_budget_exhausted(self) -> None: ...

class PrometheusMetricsCollector:
    def __init__(self, registry: Any | None = None) -> None: ...
    def record_exception(self, envelope: AgentExceptionEnvelope) -> None: ...
    def record_hard_kill(self, agent_id: str | None = None) -> None: ...
    def record_retry(self, agent_id: str | None = None) -> None: ...
    def record_budget_exhausted(self) -> None: ...
