from agentic_exception_sdk.taxonomy.envelope import AgentExceptionEnvelope
from typing import Protocol

__all__ = ['ExceptionEventSink', 'NoOpSink']

class ExceptionEventSink(Protocol):
    def emit(self, envelope: AgentExceptionEnvelope) -> None: ...
    def force_flush(self) -> None: ...

class NoOpSink:
    def emit(self, envelope: AgentExceptionEnvelope) -> None: ...
    def force_flush(self) -> None: ...
