from agentic_exception_sdk.taxonomy.envelope import AgentExceptionEnvelope

__all__ = ['StructuredLogEmitter']

class StructuredLogEmitter:
    def __init__(self, logger_name: str = 'agentic_exception_sdk.events', *, use_structlog: bool = True) -> None: ...
    def emit(self, envelope: AgentExceptionEnvelope) -> None: ...
    def force_flush(self) -> None: ...
