from agentic_exception_sdk.taxonomy.envelope import AgentExceptionEnvelope

__all__ = ["ConsensusGate", "ConsensusNotReachedError"]

class ConsensusNotReachedError(Exception): ...

class ConsensusGate:
    def __init__(self, *, threshold: int, correlation_id: str | None = None) -> None: ...
    def vote(self, envelope: AgentExceptionEnvelope | None = None) -> None: ...
    def reached(self, correlation_id: str | None = None) -> bool: ...
    def require_consensus(self, correlation_id: str | None = None) -> None: ...
    def votes_for(self, correlation_id: str | None = None) -> int: ...
    def reset(self, correlation_id: str | None = None) -> None: ...
    def clear(self) -> None: ...
    @property
    def vote_count(self) -> int: ...
    @property
    def threshold(self) -> int: ...
