from agentic_exception_sdk.taxonomy.envelope import AgentExceptionEnvelope

__all__ = ['ConsensusGate', 'ConsensusNotReachedError']

class ConsensusNotReachedError(Exception): ...

class ConsensusGate:
    def __init__(self, *, threshold: int, correlation_id: str | None = None) -> None: ...
    def vote(self, envelope: AgentExceptionEnvelope | None = None) -> None: ...
    def reached(self) -> bool: ...
    def require_consensus(self) -> None: ...
    @property
    def vote_count(self) -> int: ...
    @property
    def threshold(self) -> int: ...
