from agentic_exception_sdk.taxonomy.errors import SLAViolationError as SLAViolationError

__all__ = ['AgentSLAPolicy', 'SLAViolationError']

class AgentSLAPolicy:
    def __init__(self, *, max_seconds: float, agent_id: str) -> None: ...
    def check(self) -> None: ...
    @property
    def elapsed_seconds(self) -> float: ...
    def remaining_seconds(self) -> float: ...
