from agentic_exception_sdk.persistence.provider import PersistenceProvider, ProviderCapabilities

__all__ = ['attestation', 'get_active_provider', 'get_provider_capabilities', 'set_active_provider']

def set_active_provider(provider: PersistenceProvider) -> None: ...
def get_active_provider() -> PersistenceProvider: ...
def get_provider_capabilities() -> ProviderCapabilities: ...
def attestation() -> dict[str, bool]: ...
