from _typeshed import Incomplete
from agentic_exception_sdk.taxonomy.envelope import AgentExceptionEnvelope
from typing import Any

__all__ = ['AgentHardKillError', 'BudgetExhaustedError', 'BudgetWarningError', 'CircuitBreakerStateUnavailableError', 'CompensationPartialFailureError', 'FallbackCapableError', 'GuardRailViolationError', 'PromptInjectionError', 'SLAViolationError', 'SecurityViolationError', 'StateCorruptionError', 'ToolKindMismatchError', 'ValidationGateError']

class AgentHardKillError(BaseException):
    envelope: Incomplete
    __suppress_context__: bool
    def __init__(self, envelope: AgentExceptionEnvelope) -> None: ...
    def __reduce__(self) -> str | tuple[Any, ...]: ...
    def __deepcopy__(self, memo: dict[int, object]) -> AgentHardKillError: ...
    def __copy__(self) -> AgentHardKillError: ...

class SecurityViolationError(BaseException): ...
class PromptInjectionError(SecurityViolationError): ...
class StateCorruptionError(BaseException): ...

class CompensationPartialFailureError(BaseException):
    failed_step_ids: Incomplete
    def __init__(self, failed_step_ids: list[str]) -> None: ...

class FallbackCapableError(Exception): ...
class ToolKindMismatchError(TypeError): ...

class GuardRailViolationError(SecurityViolationError):
    canonical_tool_name: Incomplete
    def __init__(self, canonical_tool_name: str) -> None: ...

class ValidationGateError(Exception): ...
class BudgetWarningError(Exception): ...
class BudgetExhaustedError(Exception): ...
class SLAViolationError(Exception): ...
class CircuitBreakerStateUnavailableError(Exception): ...
