from enum import StrEnum

__all__ = ['EXCEPTION_OWASP_MAP', 'OWASPLLMRisk', 'classify_owasp']

class OWASPLLMRisk(StrEnum):
    LLM01_PROMPT_INJECTION = 'LLM01'
    LLM02_SENSITIVE_DISCLOSURE = 'LLM02'
    LLM03_SUPPLY_CHAIN = 'LLM03'
    LLM04_DATA_POISONING = 'LLM04'
    LLM05_IMPROPER_OUTPUT = 'LLM05'
    LLM06_EXCESSIVE_AGENCY = 'LLM06'
    LLM07_SYSTEM_PROMPT_LEAKAGE = 'LLM07'
    LLM08_VECTOR_WEAKNESSES = 'LLM08'
    LLM09_MISINFORMATION = 'LLM09'
    LLM10_UNBOUNDED_CONSUMPTION = 'LLM10'

EXCEPTION_OWASP_MAP: dict[type[BaseException], OWASPLLMRisk]

def classify_owasp(exc: BaseException) -> OWASPLLMRisk | None: ...
