from typing import Any, Protocol

__all__ = ['CheckpointStore', 'InMemoryCheckpointStore']

class CheckpointStore(Protocol):
    def save(self, *, agent_id: str, correlation_id: str | None, state: Any) -> None: ...
    def restore(self, *, agent_id: str, correlation_id: str | None) -> Any: ...

class InMemoryCheckpointStore:
    def __init__(self) -> None: ...
    def save(self, *, agent_id: str, correlation_id: str | None, state: Any) -> None: ...
    def restore(self, *, agent_id: str, correlation_id: str | None) -> Any: ...
    def clear(self) -> None: ...
