from _typeshed import Incomplete
from agentic_exception_sdk.taxonomy.envelope import AgentExceptionEnvelope
from typing import Protocol

__all__ = ['AsyncExceptionPropagationBus', 'AsyncInMemoryBus', 'ExceptionPropagationBus', 'InMemoryBus', 'PropagationBufferFullError']

class PropagationBufferFullError(RuntimeError): ...

class ExceptionPropagationBus(Protocol):
    def publish(self, envelope: AgentExceptionEnvelope) -> None: ...

class AsyncExceptionPropagationBus(Protocol):
    async def publish(self, envelope: AgentExceptionEnvelope) -> None: ...

class InMemoryBus:
    max_size: Incomplete
    bus_publish_failures_total: int
    def __init__(self, *, max_size: int = 1000) -> None: ...
    def publish(self, envelope: AgentExceptionEnvelope) -> None: ...
    def drain(self) -> list[AgentExceptionEnvelope]: ...
    @property
    def size(self) -> int: ...

class AsyncInMemoryBus:
    max_size: Incomplete
    def __init__(self, *, max_size: int = 1000) -> None: ...
    async def publish(self, envelope: AgentExceptionEnvelope) -> None: ...
    async def drain(self) -> list[AgentExceptionEnvelope]: ...
    @property
    def size(self) -> int: ...
