from _typeshed import Incomplete
from agentic_exception_sdk.taxonomy.envelope import AgentExceptionEnvelope
from typing import Protocol

__all__ = ['AsyncInMemoryDLQ', 'DeadLetterQueue', 'InMemoryDLQ']

class DeadLetterQueue(Protocol):
    def publish(self, envelope: AgentExceptionEnvelope) -> None: ...

class InMemoryDLQ:
    max_size: Incomplete
    dlq_dropped_oldest_total: int
    def __init__(self, *, max_size: int = 1000) -> None: ...
    def publish(self, envelope: AgentExceptionEnvelope) -> None: ...
    def drain(self) -> list[AgentExceptionEnvelope]: ...
    def peek(self, n: int | None = None) -> list[AgentExceptionEnvelope]: ...
    @property
    def size(self) -> int: ...

class AsyncInMemoryDLQ:
    max_size: Incomplete
    dlq_dropped_oldest_total: int
    def __init__(self, *, max_size: int = 1000) -> None: ...
    async def publish(self, envelope: AgentExceptionEnvelope) -> None: ...
    async def drain(self) -> list[AgentExceptionEnvelope]: ...
    async def peek(self, n: int | None = None) -> list[AgentExceptionEnvelope]: ...
    @property
    def size(self) -> int: ...
