from agentic_exception_sdk.taxonomy.envelope import AgentExceptionEnvelope

__all__ = ['envelope_canonical_bytes', 'envelope_canonical_sha256', 'envelope_debug_repr', 'envelope_leaf_hash', 'envelope_from_json', 'envelope_to_json']

def envelope_to_json(envelope: AgentExceptionEnvelope) -> str: ...
def envelope_from_json(json_str: str) -> AgentExceptionEnvelope: ...
def envelope_canonical_bytes(envelope: AgentExceptionEnvelope) -> bytes: ...
def envelope_canonical_sha256(envelope: AgentExceptionEnvelope) -> str: ...
def envelope_leaf_hash(envelope: AgentExceptionEnvelope) -> str: ...
def envelope_debug_repr(envelope: AgentExceptionEnvelope) -> str: ...
