from collections.abc import Callable

__all__ = ['CompensatingTransactionRegistry']

class CompensatingTransactionRegistry:
    def __init__(self) -> None: ...
    def register(self, *, correlation_id: str, step_id: str, compensate: Callable[[], None]) -> None: ...
    def compensate(self, correlation_id: str) -> None: ...
    def clear(self, correlation_id: str) -> None: ...
