from _typeshed import Incomplete
from collections.abc import Awaitable, Callable
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Protocol, TypeVar

__all__ = ['ExponentialBackoffRetry', 'InMemoryRetryInFlightTracker', 'NoOpRetry', 'RetryContext', 'RetryInFlightEntry', 'RetryInFlightTracker', 'RetryPolicy']

T = TypeVar('T')

@dataclass(frozen=True)
class RetryContext:
    correlation_id: str | None = ...
    agent_id: str | None = ...
    tool_name: str | None = ...
    idempotency_key: str | None = ...
    on_retry: Callable[[], None] | None = ...
    attempt: int = ...

@dataclass(frozen=True)
class RetryInFlightEntry:
    correlation_id: str
    agent_id: str
    tool_name: str | None
    attempt: int
    max_attempts: int
    error_type: str
    started_at: datetime
    next_retry_at: datetime | None

class RetryInFlightTracker(Protocol):
    def record_attempt(self, entry: RetryInFlightEntry) -> None: ...
    def complete(self, correlation_id: str) -> None: ...
    def list_active(self) -> list[RetryInFlightEntry]: ...

class InMemoryRetryInFlightTracker:
    def __init__(self) -> None: ...
    def record_attempt(self, entry: RetryInFlightEntry) -> None: ...
    def complete(self, correlation_id: str) -> None: ...
    def list_active(self) -> list[RetryInFlightEntry]: ...

class RetryPolicy(Protocol):
    def execute(self, fn: Callable[[], T], *, context: RetryContext | None = None) -> T: ...
    async def async_execute(self, fn: Callable[[], Awaitable[T]], *, context: RetryContext | None = None) -> T: ...

class NoOpRetry:
    def execute(self, fn: Callable[[], T], *, context: RetryContext | None = None) -> T: ...
    async def async_execute(self, fn: Callable[[], Awaitable[T]], *, context: RetryContext | None = None) -> T: ...

@dataclass
class ExponentialBackoffRetry:
    max_attempts: int = ...
    base_delay_seconds: float = ...
    max_delay_seconds: float = ...
    jitter: bool = ...
    retryable_exceptions: tuple[type[Exception], ...] = field(default_factory=Incomplete)
    max_retry_after_seconds: float = ...
    idempotency_key_fn: Callable[[RetryContext], str] | None = ...
    budget_watchdog: Any | None = ...
    inflight_tracker: RetryInFlightTracker | None = ...
    def execute(self, fn: Callable[[], T], *, context: RetryContext | None = None) -> T: ...
    async def async_execute(self, fn: Callable[[], Awaitable[T]], *, context: RetryContext | None = None) -> T: ...
