from agentic_exception_sdk.bundle import ResilienceBundle
from agentic_exception_sdk.taxonomy.envelope import AgentExceptionEnvelope, SafeContextSnapshot
from collections.abc import Awaitable, Callable, Mapping
from dataclasses import dataclass
from typing import Any, ParamSpec, TypeVar

__all__ = ['MISSING', 'ResilientCallConfig', 'async_resilient', 'extend_lineage', 'force_flush_exception_telemetry', 'resilient']

ContextSnapshotInput = SafeContextSnapshot | Mapping[str, Any]
T = TypeVar('T')
P = ParamSpec('P')
MISSING: object

@dataclass(frozen=True)
class ResilientCallConfig:
    bundle: ResilienceBundle
    tool_name: str
    agent_id: str
    correlation_id: str | None = ...
    context_snapshot: ContextSnapshotInput | None = ...
    fallback_value: object = ...
    timeout_seconds: float | None = ...
    allow_sync_llm_timeout: bool = ...

def force_flush_exception_telemetry(sink: object) -> None: ...
def resilient(bundle: ResilienceBundle, *, tool_name: str, agent_id: str, correlation_id: str | None = None, context_snapshot: ContextSnapshotInput | None = None, fallback_value: object = ..., timeout_seconds: float | None = None, allow_sync_llm_timeout: bool = False) -> Callable[[Callable[P, T]], Callable[P, T]]: ...
def async_resilient(bundle: ResilienceBundle, *, tool_name: str, agent_id: str, correlation_id: str | None = None, context_snapshot: ContextSnapshotInput | None = None, fallback_value: object = ..., timeout_seconds: float | None = None) -> Callable[[Callable[P, Awaitable[T]]], Callable[P, Awaitable[T]]]: ...
def extend_lineage(envelope: AgentExceptionEnvelope, next_agent_id: str) -> AgentExceptionEnvelope: ...
